development:
  database: db/dev.sqlite3
  adapter: sqlite3
  timeout: 5000
  pool: 5

test:
  database: db/test.sqlite3
  adapter: sqlite3
  timeout: 5000
  pool: 5

production:
  database: db/prod.sqlite3
  adapter: sqlite3
  timeout: 5000
  pool: 5